const NetworkConstants = {
	BASE_URL : 'https://launchlibrary.net/1.4/',
	NEXT10: 'next=10',
	LAUNCH: 'launch',
	START_DATE: 'startdate',
	END_DATE: 'enddate',
	LIMIT: 'limit',
	OFFSET: 'offset',
	LAUNCHES: 'launches',
	TOTAL: 'total',
	COUNT: 'count',
	NAME: 'name',
	WINDOW_START: 'windowstart',
	LAUNCH_FILTER: '&fields=windowstart,name,rocket,missions,location',
	ROCKET: 'rocket',
	IMAGE_SIZES: 'imageSizes',
	IMAGE_URL: 'imageURL',
	DATE: 'date',
	ID: 'id',
	LAUNCH_STATUS: 'launchstatus',
	TYPES: 'types',
	MISSIONS: 'missions',
	DESCRIPTION: 'description',
	TYPE_NAME: 'typeName',
	UID: 'uid',
	LOCATION: 'location',
	PADS: 'pads'
}

export default NetworkConstants;